language: java

env:
  global:
  - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)-SNAPSHOT"

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8 
  
stages:
- build
- name: publish
# if: branch = master AND NOT type = pull_request
  
jobs:
  include:
    - stage: build
      script: mvn -B verify
    - stage: publish
      script: mvn -B site -P snapshot