language: java

env:
  global:
  - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)-SNAPSHOT"

addons:
  sonarcloud:
    organization: "ianagbip1oti-github"

before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./etc/extract_secrets.sh; fi'

stages:
- build
- name: snapshot
  if: branch = master AND NOT type = pull_request
- name: release
  if: tag =~ ^\d+\.\d+\.\d+$
  
jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      script: mvn -B verify
    - jdk: oraclejdk9
      script: mvn -B verify
    - jdk: openjdk8
      script: mvn -B verify
    - stage: snapshot
      jdk: openjdk8
      script: mvn -s etc/settings.xml -B deploy -P release
    - jdk: openjdk8
      git:
        depth: false
      script: mvn -B verify sonar:sonar
    - stage: release
      jdk: openjdk8
      env:
        - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)"
      script: mvn -s etc/settings.xml -B deploy -P release

